from __future__ import annotations
# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# fmt: off
# -- template metadata.py.jinja --


PRISMA_MODELS: set[str] = {
    'User',
    'Battery',
    'Prediction',
    'ChainRecord',
    'AuditLog',
}

RELATIONAL_FIELD_MAPPINGS: dict[str, dict[str, str]] = {
    'User': {
        'predictions': 'Prediction',
        'audit_logs': 'AuditLog',
    },
    'Battery': {
        'predictions': 'Prediction',
        'chain_records': 'ChainRecord',
    },
    'Prediction': {
        'battery': 'Battery',
        'user': 'User',
        'chain_records': 'ChainRecord',
    },
    'ChainRecord': {
        'prediction': 'Prediction',
        'battery': 'Battery',
    },
    'AuditLog': {
        'actor': 'User',
    },
}

# fmt: on